/**
 * GENERATED by scripts/embed-jwks.mjs. Do not edit by hand.
 *
 * Last-known public signing keys per issuer, embedded at build time so ID
 * tokens keep verifying while the JWKS URL is unreachable. Public parts only.
 *
 * Empty until the issuer is on production: `npm run embed-keys` fills it
 * (the publish workflow runs it before every build).
 */
import type { JWK } from 'jose';

export const EMBEDDED_JWKS = {} as const;

export function embeddedKeysFor(issuer: string): JWK[] {
  const normalized = issuer.replace(/\/+$/, '');
  const keys = (EMBEDDED_JWKS as Record<string, readonly JWK[]>)[normalized];
  return keys ? keys.map((k) => ({ ...k })) : [];
}
