#!/usr/bin/env node
/**
 * Snapshot the published JWKS of each known issuer into
 * packages/ac-auth/src/embedded-keys.ts.
 *
 * Why: @alternatefutures/ac-auth verifies ID tokens offline with the issuer's
 * public keys. A build carries the keys that were public when it shipped, so
 * a token still verifies while the JWKS URL is unreachable (plan M4 "cheap
 * first"). Retired keys drop out of the JWKS after 7 days; the snapshot only
 * ever contains public parts.
 *
 * Best effort: an issuer that cannot be reached keeps its existing snapshot.
 * Run before every publish (npm-publish.yml) and whenever keys rotate.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(here, '../packages/ac-auth/src/embedded-keys.ts');

const ISSUERS = (process.env.AUTH_SDK_EMBED_ISSUERS || 'https://auth.alternatefutures.ai,https://auth.staging.alternatefutures.ai')
  .split(',')
  .map((s) => s.trim().replace(/\/+$/, ''))
  .filter(Boolean);

function readExisting() {
  try {
    const src = readFileSync(TARGET, 'utf8');
    const m = /EMBEDDED_JWKS[^=]*=\s*(\{[\s\S]*?\})\s+as const/.exec(src);
    return m ? JSON.parse(m[1]) : {};
  } catch {
    return {};
  }
}

function isPublicJwk(k) {
  if (!k || typeof k !== 'object' || !k.kid || !k.kty) return false;
  for (const priv of ['d', 'p', 'q', 'dp', 'dq', 'qi', 'k']) if (priv in k) return false;
  return true;
}

const snapshot = readExisting();
let changed = false;
for (const issuer of ISSUERS) {
  const url = `${issuer}/.well-known/jwks.json`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const body = await res.json();
    const keys = Array.isArray(body?.keys) ? body.keys.filter(isPublicJwk) : [];
    if (keys.length === 0) throw new Error('no public keys in the document');
    snapshot[issuer] = keys;
    changed = true;
    console.log(`embedded ${keys.length} key(s) for ${issuer}`);
  } catch (error) {
    console.warn(`skipping ${issuer}: ${error instanceof Error ? error.message : String(error)} (keeping the existing snapshot)`);
  }
}

const generatedAt = new Date().toISOString();
const out = `/**
 * GENERATED by scripts/embed-jwks.mjs at ${generatedAt}. Do not edit by hand.
 *
 * Last-known public signing keys per issuer, embedded at build time so ID
 * tokens keep verifying while the JWKS URL is unreachable. Public parts only.
 */
import type { JWK } from 'jose';

export const EMBEDDED_JWKS = ${JSON.stringify(snapshot, null, 2)} as const;

export function embeddedKeysFor(issuer: string): JWK[] {
  const normalized = issuer.replace(/\\/+$/, '');
  const keys = (EMBEDDED_JWKS as Record<string, readonly JWK[]>)[normalized];
  return keys ? keys.map((k) => ({ ...k })) : [];
}
`;
writeFileSync(TARGET, out);
console.log(`${changed ? 'updated' : 'rewrote'} ${TARGET}`);
